import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

export async function prepareElectronE2EUserData() {
  const userDataDir = await fs.mkdtemp(path.join(os.tmpdir(), "lawmind-e2e-userdata-"));
  const workspaceDir = await fs.mkdtemp(path.join(os.tmpdir(), "lawmind-e2e-workspace-"));
  const lawMindRoot = path.join(userDataDir, "LawMind");
  await fs.mkdir(path.join(workspaceDir, "audit"), { recursive: true });
  await fs.mkdir(lawMindRoot, { recursive: true });
  await fs.writeFile(
    path.join(lawMindRoot, "desktop-config.json"),
    JSON.stringify({ workspaceDir, retrievalMode: "single" }, null, 2),
    "utf8",
  );
  await fs.writeFile(
    path.join(workspaceDir, "lawmind.config.json"),
    JSON.stringify({ schemaVersion: 1 }, null, 2),
    "utf8",
  );

  const draftsDir = path.join(workspaceDir, "drafts");
  await fs.mkdir(draftsDir, { recursive: true });
  const now = new Date().toISOString();
  await fs.writeFile(
    path.join(draftsDir, "e2e-draft-1.json"),
    JSON.stringify(
      {
        taskId: "e2e-draft-1",
        title: "E2E Electron draft",
        output: "docx",
        templateId: "word/legal-memo-default",
        sections: [{ heading: "摘要", body: "E2E body" }],
        reviewNotes: [],
        reviewStatus: "pending",
        createdAt: now,
      },
      null,
      2,
    ),
    "utf8",
  );

  return { userDataDir, workspaceDir };
}

/**
 * 为需要真实本地服务的契约化 E2E 准备用户数据：
 * - 写入 .env.lawmind（假模型 key、签批/导出 bypass、测试路由开关）
 * - 写入 models.json 使默认模型显示为已验证，避免 API 向导拦截首跑对话框
 * - 其余目录结构与 prepareElectronE2EUserData 保持一致
 */
export async function prepareElectronE2EUserDataWithEnv(opts = {}) {
  const { userDataDir, workspaceDir } = await prepareElectronE2EUserData();
  const lawMindRoot = path.join(userDataDir, "LawMind");
  const now = new Date().toISOString();

  const envLines = [
    "# Generated by LawMind E2E contract harness",
    "LAWMIND_AGENT_API_KEY=e2e-fake-key",
    "LAWMIND_AGENT_MODEL=qwen-plus",
    "LAWMIND_QWEN_MODEL=qwen-plus",
    "LAWMIND_RETRIEVAL_MODE=single",
    "LAWMIND_ALLOW_CHECKLIST_BYPASS=1",
    "LAWMIND_ALLOW_RENDER_GATE_BYPASS=1",
    "LAWMIND_ENABLE_E2E_TEST_ROUTES=1",
    "LAWMIND_SKIP_API_AUTH=1",
    "LAWMIND_AGENT_BASE_URL=http://127.0.0.1:1",
  ];
  await fs.writeFile(path.join(lawMindRoot, ".env.lawmind"), envLines.join("\n") + "\n", "utf8");

  await fs.writeFile(
    path.join(lawMindRoot, "models.json"),
    JSON.stringify(
      {
        schemaVersion: 2,
        customModels: [],
        defaultModelId: "builtin:qwen-plus",
        verifications: {
          "builtin:qwen-plus": {
            verifiedAt: now,
            latencyMs: 1,
            model: "qwen-plus",
            baseUrl: "http://127.0.0.1:1",
          },
        },
      },
      null,
      2,
    ),
    "utf8",
  );

  if (opts?.matterId) {
    await fs.mkdir(path.join(workspaceDir, "cases", String(opts.matterId)), { recursive: true });
  }

  return { userDataDir, workspaceDir, lawMindRoot };
}
