/**
 * All 41 CUAD v1 categories (Hendrycks et al. 2021, Atticus category list).
 *
 * Texts are original Chinese clauses, not EDGAR contracts. Answer strings are
 * derived from the span, which is the CUAD rule. Yes/No categories are Yes
 * only when a responsive span exists.
 */

export type CuadAnswerKind = "yes_no" | "span" | "date";

export type CuadOfficialClause = {
  /** 1–41, the published category order. */
  index: number;
  id: string;
  officialName: string;
  answerKind: CuadAnswerKind;
  /** CUAD group. Categories in one group may share a clause. */
  group: number | null;
  anchor: string;
  /** String derived from the span. For yes/no this is the responsive phrase. */
  answer: string;
  excerpt: string;
  absent: string;
};

export const CUAD_OFFICIAL_CLAUSES: readonly CuadOfficialClause[] = [
  {
    index: 1,
    id: "document_name",
    officialName: "Document Name",
    answerKind: "span",
    group: null,
    anchor: "clause:合同名称",
    answer: "软件许可合同",
    excerpt: "本合同名称为软件许可合同。",
    absent: "双方应诚信履行。",
  },
  {
    index: 2,
    id: "parties",
    officialName: "Parties",
    answerKind: "span",
    group: null,
    anchor: "clause:当事人",
    answer: "上海示例科技有限公司",
    excerpt: "甲方：上海示例科技有限公司。乙方：杭州示例贸易有限公司。",
    absent: "双方盖章后生效。",
  },
  {
    index: 3,
    id: "agreement_date",
    officialName: "Agreement Date",
    answerKind: "date",
    group: 1,
    anchor: "clause:签署日",
    answer: "2024年3月1日",
    excerpt: "本合同于2024年3月1日签署。",
    absent: "签署地点为上海市。",
  },
  {
    index: 4,
    id: "effective_date",
    officialName: "Effective Date",
    answerKind: "date",
    group: 1,
    anchor: "clause:生效",
    answer: "2024年3月1日",
    excerpt: "本合同自2024年3月1日起生效。",
    absent: "附件与本合同具有同等效力。",
  },
  {
    index: 5,
    id: "expiration_date",
    officialName: "Expiration Date",
    answerKind: "date",
    group: 1,
    anchor: "clause:到期",
    answer: "2027年3月1日",
    excerpt: "本合同初始期限于2027年3月1日届满。",
    absent: "任何一方可提前协商变更。",
  },
  {
    index: 6,
    id: "renewal_term",
    officialName: "Renewal Term",
    answerKind: "span",
    group: 1,
    anchor: "clause:续展",
    answer: "自动续展一年",
    excerpt: "期限届满后自动续展一年，除非一方按约通知不续展。",
    absent: "合同期限为三年。",
  },
  {
    index: 7,
    id: "notice_to_terminate_renewal",
    officialName: "Notice to Terminate Renewal",
    answerKind: "span",
    group: 1,
    anchor: "clause:续展通知",
    answer: "届满前六十日书面通知",
    excerpt: "不续展的，应在届满前六十日书面通知对方。",
    absent: "通知地址变更应书面告知。",
  },
  {
    index: 8,
    id: "governing_law",
    officialName: "Governing Law",
    answerKind: "span",
    group: null,
    anchor: "clause:管辖",
    answer: "中华人民共和国法律",
    excerpt: "本合同适用中华人民共和国法律。",
    absent: "双方应按约全面履行。",
  },
  {
    index: 9,
    id: "most_favored_nation",
    officialName: "Most Favored Nation",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:最惠",
    answer: "不得优于给予乙方的条件",
    excerpt: "甲方给予任何第三方的价格不得优于给予乙方的条件。",
    absent: "价格由双方另行书面确认。",
  },
  {
    index: 10,
    id: "non_compete",
    officialName: "Non-Compete",
    answerKind: "yes_no",
    group: 2,
    anchor: "clause:竞业限制",
    answer: "离职后两年内不得",
    excerpt: "劳动者离职后两年内不得在同类产品用人单位任职。",
    absent: "劳动者应按时完成工作任务。",
  },
  {
    index: 11,
    id: "exclusivity",
    officialName: "Exclusivity",
    answerKind: "yes_no",
    group: 2,
    anchor: "clause:独家",
    answer: "独家经销",
    excerpt: "甲方指定乙方为产品在华东地区的独家经销商。",
    absent: "乙方可在其经营场所销售甲方产品。",
  },
  {
    index: 12,
    id: "no_solicit_customers",
    officialName: "No-Solicit of Customers",
    answerKind: "yes_no",
    group: 2,
    anchor: "clause:禁揽客户",
    answer: "不得招揽对方客户",
    excerpt: "任何一方在合同期内及终止后一年内不得招揽对方客户。",
    absent: "双方可互相介绍业务机会。",
  },
  {
    index: 13,
    id: "competitive_restriction_exception",
    officialName: "Competitive Restriction Exception",
    answerKind: "yes_no",
    group: 2,
    anchor: "clause:竞业例外",
    answer: "已持有的被动财务投资不在此限",
    excerpt: "竞业限制不适用于签约前已持有的被动财务投资不在此限的股权。",
    absent: "乙方应遵守保密义务。",
  },
  {
    index: 14,
    id: "no_solicit_employees",
    officialName: "No-Solicit of Employees",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:禁挖员工",
    answer: "不得招揽对方员工",
    excerpt: "任何一方不得招揽对方员工，但公开招聘回应者不在此限。",
    absent: "双方可开展联合培训。",
  },
  {
    index: 15,
    id: "non_disparagement",
    officialName: "Non-Disparagement",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:不得贬损",
    answer: "不得公开贬损对方",
    excerpt: "任何一方不得公开贬损对方的商誉或产品。",
    absent: "双方应依约开具发票。",
  },
  {
    index: 16,
    id: "termination_for_convenience",
    officialName: "Termination for Convenience",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:解除",
    answer: "提前三十日书面通知解除",
    excerpt: "甲方有权提前三十日书面通知解除本合同，且无需说明理由。",
    absent: "本合同自双方盖章之日起生效。",
  },
  {
    index: 17,
    id: "rofr",
    officialName: "Right of First Refusal, Offer or Negotiation (ROFR/ROFO/ROFN)",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:优先购买权",
    answer: "优先购买权",
    excerpt: "甲方转让本协议项下技术前，应给予乙方优先购买权。",
    absent: "转让须符合出口管制规定。",
  },
  {
    index: 18,
    id: "change_of_control",
    officialName: "Change of Control",
    answerKind: "yes_no",
    group: 3,
    anchor: "clause:控制权变更",
    answer: "控制权发生变更",
    excerpt: "甲方控制权发生变更的，应在三十日内书面通知乙方。",
    absent: "甲方变更通知地址的，应书面告知乙方。",
  },
  {
    index: 19,
    id: "anti_assignment",
    officialName: "Anti-Assignment",
    answerKind: "yes_no",
    group: 3,
    anchor: "clause:转让",
    answer: "事先书面同意",
    excerpt: "未经对方事先书面同意，不得转让本合同项下的权利义务。",
    absent: "本合同对双方承继人具有约束力。",
  },
  {
    index: 20,
    id: "revenue_profit_sharing",
    officialName: "Revenue/Profit Sharing",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:分成",
    answer: "按净销售额的百分之十分成",
    excerpt: "乙方应按净销售额的百分之十分成向甲方支付。",
    absent: "发票应在付款前开具。",
  },
  {
    index: 21,
    id: "price_restriction",
    officialName: "Price Restriction",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:价格限制",
    answer: "不得单方提高价格",
    excerpt: "合同期内甲方不得单方提高价格，调价须双方书面同意。",
    absent: "货款应于交付后三十日内付清。",
  },
  {
    index: 22,
    id: "minimum_commitment",
    officialName: "Minimum Commitment",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:最低采购",
    answer: "最低采购量为人民币伍佰万元",
    excerpt: "乙方每一合同年度的最低采购量为人民币伍佰万元。",
    absent: "采购数量以订单为准。",
  },
  {
    index: 23,
    id: "volume_restriction",
    officialName: "Volume Restriction",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:数量限制",
    answer: "不得超过附件约定的年度上限",
    excerpt: "乙方使用量不得超过附件约定的年度上限，超出须另行同意。",
    absent: "乙方应按订单数量收货。",
  },
  {
    index: 24,
    id: "ip_ownership_assignment",
    officialName: "IP Ownership Assignment",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:知识产权",
    answer: "知识产权归甲方所有",
    excerpt: "履行本合同产生的职务成果，其知识产权归甲方所有。",
    absent: "双方各自保留签约前已有的知识产权。",
  },
  {
    index: 25,
    id: "joint_ip_ownership",
    officialName: "Joint IP Ownership",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:共有知识产权",
    answer: "双方共有",
    excerpt: "双方共同开发的改进技术，其知识产权由双方共有。",
    absent: "背景知识产权仍归原权利人。",
  },
  {
    index: 26,
    id: "license_grant",
    officialName: "License Grant",
    answerKind: "yes_no",
    group: 4,
    anchor: "clause:许可",
    answer: "非独占许可",
    excerpt: "甲方授予乙方一项不可转让的非独占许可，仅限约定区域。",
    absent: "乙方应妥善保管技术资料。",
  },
  {
    index: 27,
    id: "non_transferable_license",
    officialName: "Non-Transferable License",
    answerKind: "yes_no",
    group: 4,
    anchor: "clause:许可不得转让",
    answer: "许可不得再许可",
    excerpt: "本许可不得再许可或转让给任何第三方。",
    absent: "乙方可在内部员工中使用。",
  },
  {
    index: 28,
    id: "affiliate_license_licensor",
    officialName: "Affiliate IP License-Licensor",
    answerKind: "yes_no",
    group: 4,
    anchor: "clause:许可方关联方",
    answer: "包括许可方关联方的知识产权",
    excerpt: "本许可包括许可方关联方的知识产权，以附件清单为限。",
    absent: "许可费按季度结算。",
  },
  {
    index: 29,
    id: "affiliate_license_licensee",
    officialName: "Affiliate IP License-Licensee",
    answerKind: "yes_no",
    group: 4,
    anchor: "clause:被许可方关联方",
    answer: "被许可方关联方可使用",
    excerpt: "被许可方关联方可使用本许可，但不得再对外转让。",
    absent: "使用报告应按季度提交。",
  },
  {
    index: 30,
    id: "unlimited_license",
    officialName: "Unlimited/All-You-Can-Eat License",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:不限量许可",
    answer: "企业不限量使用",
    excerpt: "在许可期内，乙方及其内部用户可企业不限量使用本软件。",
    absent: "超出约定席位须另购。",
  },
  {
    index: 31,
    id: "irrevocable_or_perpetual_license",
    officialName: "Irrevocable or Perpetual License",
    answerKind: "yes_no",
    group: 4,
    anchor: "clause:永久许可",
    answer: "不可撤销的永久许可",
    excerpt: "费用付清后，甲方授予乙方不可撤销的永久许可。",
    absent: "许可按年续费。",
  },
  {
    index: 32,
    id: "source_code_escrow",
    officialName: "Source Code Escrow",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:源码托管",
    answer: "源代码交由第三方托管",
    excerpt: "甲方应将源代码交由第三方托管，并在破产时向乙方释放。",
    absent: "乙方不得反编译目标代码。",
  },
  {
    index: 33,
    id: "post_termination_services",
    officialName: "Post-Termination Services",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:终止后服务",
    answer: "九十日内继续提供过渡协助",
    excerpt: "合同终止后，乙方应在九十日内继续提供过渡协助。",
    absent: "合同终止后双方不再负有义务。",
  },
  {
    index: 34,
    id: "audit_rights",
    officialName: "Audit Rights",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:查账",
    answer: "查阅与本许可有关的账册",
    excerpt: "许可方有权在合理通知后查阅与本许可有关的账册。",
    absent: "被许可方应按季度提交使用报告。",
  },
  {
    index: 35,
    id: "uncapped_liability",
    officialName: "Uncapped Liability",
    answerKind: "yes_no",
    group: 5,
    anchor: "clause:责任不封顶",
    answer: "赔偿责任不设上限",
    excerpt: "因保密违约造成的损失，赔偿责任不设上限。",
    absent: "一般违约以合同总价为限。",
  },
  {
    index: 36,
    id: "cap_on_liability",
    officialName: "Cap on Liability",
    answerKind: "yes_no",
    group: 5,
    anchor: "clause:责任上限",
    answer: "以已付合同总价为限",
    excerpt: "一方的赔偿责任以已付合同总价为限，间接损失不予赔偿。",
    absent: "一方违约的，应赔偿对方损失。",
  },
  {
    index: 37,
    id: "liquidated_damages",
    officialName: "Liquidated Damages",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:违约金",
    answer: "每日万分之五",
    excerpt: "逾期付款的，应按欠付金额每日万分之五支付违约金。",
    absent: "货款应于交付后三十日内付清。",
  },
  {
    index: 38,
    id: "warranty_duration",
    officialName: "Warranty Duration",
    answerKind: "span",
    group: null,
    anchor: "clause:质保",
    answer: "二十四个月",
    excerpt: "质保期为验收合格之日起二十四个月。",
    absent: "甲方应在交付时提供合格证明。",
  },
  {
    index: 39,
    id: "insurance",
    officialName: "Insurance",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:保险",
    answer: "投保产品责任险",
    excerpt: "乙方应投保产品责任险，并在保单中列明甲方为受益人。",
    absent: "货物毁损风险自交付时转移。",
  },
  {
    index: 40,
    id: "covenant_not_to_sue",
    officialName: "Covenant Not to Sue",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:不争议",
    answer: "不得挑战对方知识产权的有效性",
    excerpt: "乙方不得挑战对方知识产权的有效性，但履行争议不在此限。",
    absent: "双方可通过仲裁解决合同争议。",
  },
  {
    index: 41,
    id: "third_party_beneficiary",
    officialName: "Third Party Beneficiary",
    answerKind: "yes_no",
    group: null,
    anchor: "clause:第三人",
    answer: "第三方不得依本合同主张权利",
    excerpt: "除本合同明确约定外，第三方不得依本合同主张权利。",
    absent: "本合同自双方盖章之日起生效。",
  },
];

/** One clause answering two Group-1 questions, as CUAD allows. */
export const CUAD_GROUP1_SHARED =
  "本合同于2024年3月1日生效，初始期限于2027年3月1日届满，其后自动续展一年；不续展的，应在届满前六十日书面通知。";
