/**
 * Built-in named workflows (Claude for Legal / Suzie Law).
 * Copied into `<workspace>/lawmind/workflows/` when missing (see ensure-workflow-seeds.ts).
 */

import type { WorkspaceWorkflowTemplateFile } from "./workspace-workflow-templates.js";

export const BUILTIN_WORKFLOW_TEMPLATES: WorkspaceWorkflowTemplateFile[] = [
  {
    id: "training-ppt",
    name: "培训 PPT",
    namedAgent: "Training Deck Writer",
    description: "把一个主题整理成培训课件大纲与 PPT 草稿，适合内部培训或客户分享。",
    practiceArea: "client",
    deliverableType: "ppt.training",
    riskLevel: "low",
    audience: "solo",
    kind: "office",
    starterPrompt:
      "请帮我做一份培训 PPT。主题是：\n\n受众是：\n预计时长：\n希望风格：专业、清楚、适合律师讲解。\n\n请先 deep_research 或整理要点并给出课件大纲（待我确认），再 draft_document / execute_workflow 生成可导出 PPT。若使用案件材料请先脱敏并注明「已脱敏」。",
    steps: [
      {
        stepId: "research",
        assignee: "client_communicator",
        task: "收集培训要点与公开来源（可用 deep_research；案件材料须已脱敏）",
        dependsOn: [],
        autoApprove: false,
      },
      {
        stepId: "outline_confirm",
        assignee: "client_communicator",
        task: "输出课件大纲并等待律师确认（research_outline_confirm）；未确认不得扩写幻灯片正文",
        dependsOn: ["research"],
        autoApprove: false,
      },
      {
        stepId: "deck",
        assignee: "client_communicator",
        task: "大纲确认后 draft_document（ppt.training）并走验收清单",
        dependsOn: ["outline_confirm"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "office-research-report",
    name: "研究报告 / 内部分享",
    namedAgent: "Research Memo Writer",
    description: "把一个法律或行业主题整理成学习型调研简报或内部分享材料。",
    practiceArea: "compliance",
    deliverableType: "report.learning",
    riskLevel: "medium",
    audience: "solo",
    kind: "office",
    starterPrompt:
      "请帮我写一份学习型调研简报/内部分享材料。主题是：\n\n用途是：\n读者是：\n需要覆盖的重点：\n\n请先 deep_research 并列出研究大纲（待我确认），再起草正文；制度要点请区分效力层级。",
    steps: [
      {
        stepId: "research",
        assignee: "compliance_researcher",
        task: "深度研究并落盘证据大纲（deep_research / research_task）",
        dependsOn: [],
        autoApprove: false,
      },
      {
        stepId: "outline_confirm",
        assignee: "compliance_researcher",
        task: "等待律师确认研究大纲（research_outline_confirm）",
        dependsOn: ["research"],
        autoApprove: false,
      },
      {
        stepId: "report",
        assignee: "compliance_researcher",
        task: "大纲确认后起草学习型调研简报（report.learning）并附来源",
        dependsOn: ["outline_confirm"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "speech-or-lecture-draft",
    name: "讲稿 / 培训讲义",
    namedAgent: "Lecture Draft Writer",
    description: "起草讲话稿、课程讲义或活动发言材料，默认不绑定案件。",
    practiceArea: "client",
    deliverableType: "document.speech",
    riskLevel: "low",
    audience: "solo",
    kind: "office",
    starterPrompt:
      "请帮我起草一份讲稿/培训讲义。主题是：\n\n场合是：\n听众是：\n时长约：\n语气要求：\n\n请先给结构，再写完整草稿。",
    steps: [
      {
        stepId: "draft",
        assignee: "client_communicator",
        task: "起草讲稿或培训讲义",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "nda-triage",
    name: "保密协议初审",
    namedAgent: "NDA Triager",
    description: "对 inbound NDA 做风险分级与要点摘要；起草后互审再交律师。",
    practiceArea: "commercial",
    deliverableType: "contract.review",
    riskLevel: "medium",
    audience: "solo",
    kind: "matter",
    starterPrompt: "请对当前案件中的保密协议做初审：列出对己方不利条款、缺失定义与建议追问项。",
    acceptancePackRequired: true,
    requiredSources: ["NDA 文本"],
    steps: [
      {
        stepId: "draft",
        assignee: "contract_review",
        assigneeRoleId: "contract_review",
        task: "审查 NDA 并输出 GREEN/YELLOW/RED 分级与条款摘要（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
      {
        stepId: "peer",
        assignee: "general_default",
        assigneeRoleId: "general_default",
        task: "互审 NDA 初审结论：核对风险分级是否过宽/过严，列出须律师拍板项（matterId={{matterId}}）",
        dependsOn: ["draft"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "contract-review",
    name: "合同审查意见",
    namedAgent: "Contract Review Analyst",
    description: "起草合同审查意见 → 互审 → 交律师签批（多步团队流水线）。",
    practiceArea: "commercial",
    deliverableType: "contract.review",
    riskLevel: "medium",
    audience: "solo",
    kind: "matter",
    starterPrompt: "请审查本案主合同，输出分章节审查意见与风险等级。",
    acceptancePackRequired: true,
    requiredSources: ["主合同"],
    steps: [
      {
        stepId: "draft",
        assignee: "contract_review",
        assigneeRoleId: "contract_review",
        task: "生成合同审查意见初稿（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
      {
        stepId: "peer",
        assignee: "general_default",
        assigneeRoleId: "general_default",
        reviewBy: undefined,
        task: "互审合同审查意见：核对风险分级、必改项完整性与引用锚定（matterId={{matterId}}）",
        dependsOn: ["draft"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "mail-contract-redline",
    name: "邮件合同审阅改稿",
    namedAgent: "Mail Contract Redliner",
    description:
      "以邮件合同附件为基线：.doc/.docx 一等公民，短路径最小改稿 + 审阅痕迹；PDF/图片等走意见书。准备待律师批准的外发（不自动发送）。",
    practiceArea: "commercial",
    deliverableType: "contract.general",
    riskLevel: "medium",
    audience: "solo",
    kind: "matter",
    starterPrompt:
      "短路径：基线路径已给 → 最小改 → render_tracked_draft → prepare_outbound_mail。禁止反复检索案卷/项目文件。",
    acceptancePackRequired: true,
    requiredSources: ["邮件合同附件"],
    // 自动化短路径：仅预批准「待拍板」类工具（strict Edition 下不打断短路径）；
    // send_email 仍须律师在在办拍板，不在此列。
    preApproveToolNames: ["apply_surgical_edits", "render_tracked_draft", "prepare_outbound_mail"],
    steps: [
      {
        stepId: "redline",
        assignee: "contract_review",
        assigneeRoleId: "contract_review",
        task: [
          "{{instruction}}",
          "",
          "短路径执行约束（勿 search_workspace/read_project_file/list_mail_*；勿再问审查重点/己方立场）：",
          "analyze_document 一次（通读）→ draft/update_draft（contract_edit_baseline_path + seed）→ apply_surgical_edits（跨度硬门禁：最短字/词锚定 + craft_check；能改几个字就只改几个字；段内只改有问题的句子；条数不限；其余 deferred）→ render_tracked_draft 写入源文件同目录（原名_日期_01.docx，不打开 Word）。",
          "整句/整段/整节删除重写会被硬门禁跳过。空修订不得 render（redlinePending=0）。勿另开完整意见书流程。",
        ].join("\n"),
        dependsOn: [],
        autoApprove: true,
      },
      {
        stepId: "handoff",
        assignee: "contract_review",
        assigneeRoleId: "contract_review",
        task: "prepare_outbound_mail（附件=上一步 cases/{{matterId}}/ 审阅稿路径）；禁止 send_email；交律师签批。",
        dependsOn: ["redline"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "vendor-agreement-review",
    name: "供应商协议审查",
    namedAgent: "Vendor Agreement Reviewer",
    description: "针对采购/服务协议的重点条款、责任上限与终止权做结构化审查。",
    practiceArea: "commercial",
    deliverableType: "contract.review",
    riskLevel: "medium",
    audience: "firm",
    kind: "matter",
    starterPrompt: "请审查供应商协议：付款、交付、赔偿上限、知识产权与终止条款。",
    acceptancePackRequired: true,
    requiredSources: ["供应商协议"],
    steps: [
      {
        stepId: "review",
        assignee: "contract_review",
        assigneeRoleId: "contract_review",
        task: "供应商协议条款审查与风险清单（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "demand-letter",
    name: "律师函起草",
    namedAgent: "Demand Letter Drafter",
    description: "根据事实与诉求生成结构化律师函草稿，含待补充项清单。",
    practiceArea: "litigation",
    deliverableType: "letter.demand",
    riskLevel: "high",
    audience: "solo",
    kind: "matter",
    starterPrompt: "请为本案起草律师函：先列出需律师确认的事实与诉求，再生成完整正文框架。",
    acceptancePackRequired: true,
    steps: [
      {
        stepId: "draft",
        assignee: "litigation_drafter",
        task: "起草律师函（matterId={{matterId}}），交付类型 letter.demand",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "matter-chronology",
    name: "案件时间线整理",
    namedAgent: "Chronology Builder",
    description: "按时间顺序整理关键事件、证据与待证事实（证据时间线）。",
    practiceArea: "litigation",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    kind: "matter",
    starterPrompt: "请整理本案时间线：每个节点注明来源、争议点与下一步动作建议。",
    steps: [
      {
        stepId: "chronology",
        assignee: "case_analyst",
        task: "整理案件时间线与证据索引（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: true,
      },
    ],
  },
  {
    id: "evidence-index",
    name: "证据索引编制",
    namedAgent: "Evidence Indexer",
    description: "为案件卷宗建立证据目录与证明目的对照表。",
    practiceArea: "litigation",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    kind: "matter",
    starterPrompt: "请根据现有材料编制证据索引：编号、来源、证明目的、待补强项。",
    steps: [
      {
        stepId: "index",
        assignee: "case_analyst",
        task: "编制证据索引表（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: true,
      },
    ],
  },
  {
    id: "due-diligence-review",
    name: "尽调审查表",
    namedAgent: "Due Diligence Reviewer",
    description: "多文档尽调：合同、函件与公开信息对照审查矩阵问题列。",
    practiceArea: "due_diligence",
    deliverableType: "contract.review",
    riskLevel: "high",
    audience: "firm",
    kind: "matter",
    starterPrompt: "请启动尽调审查：先列出材料清单，再按尽调问题列逐项标注风险与来源。",
    acceptancePackRequired: true,
    requiredSources: ["目标公司材料包"],
    steps: [
      {
        stepId: "inventory",
        assignee: "case_analyst",
        task: "整理尽调材料清单与缺口（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: true,
      },
      {
        stepId: "review",
        assignee: "contract_review",
        assigneeRoleId: "contract_review",
        task: "按尽调审查表输出分文档风险摘要（matterId={{matterId}}）",
        dependsOn: ["inventory"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "client-update-memo",
    name: "客户邮件摘要",
    namedAgent: "Client Update Writer",
    description: "面向客户的进展说明与下一步安排（邮件/备忘录语气）。",
    practiceArea: "client",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    kind: "matter",
    schedulable: true,
    starterPrompt: "请起草给客户的本案进展备忘录：已完成工作、当前风险、需客户确认事项与时间表。",
    steps: [
      {
        stepId: "memo",
        assignee: "client_communicator",
        task: "起草客户进展备忘录（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "compliance-research-memo",
    name: "合规研究报告",
    namedAgent: "Regulatory Research Analyst",
    description:
      "针对监管问题做 URL/权威检索，输出可复核涉外合规卷宗备忘录（含管辖矩阵与来源附录）。",
    practiceArea: "compliance",
    deliverableType: "report.compliance",
    riskLevel: "medium",
    audience: "firm",
    kind: "matter",
    starterPrompt:
      "请就本案监管问题做合规研究卷宗：问题陈述、简要结论、管辖区效力矩阵、按风险域发现、行动建议与来源附录。若有官网/法规 URL 请先 url_dossier / deep_research；不确定处标 [VERIFY]。请先给大纲待我确认后再写正文。",
    steps: [
      {
        stepId: "research",
        assignee: "compliance_researcher",
        task: "URL/权威检索与深度研究（matterId={{matterId}}；deep_research / url_dossier；deliverableType=report.compliance）",
        dependsOn: [],
        autoApprove: false,
      },
      {
        stepId: "outline_confirm",
        assignee: "compliance_researcher",
        task: "输出研究大纲并等待律师确认（research_outline_confirm）；未确认不得扩写正文",
        dependsOn: ["research"],
        autoApprove: false,
      },
      {
        stepId: "memo",
        assignee: "compliance_researcher",
        task: "大纲确认后起草合规卷宗备忘录（含管辖矩阵与来源附录）；可用 existing_task_id 续跑",
        dependsOn: ["outline_confirm"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "renewal-monitor",
    name: "合同续签监控",
    namedAgent: "Contract Renewal Monitor",
    description: "扫描主合同中的到期、续签与终止条款，输出续签提醒备忘；需要时可预约定期再跑。",
    practiceArea: "commercial",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    kind: "matter",
    schedulable: true,
    starterPrompt:
      "请扫描本案主合同的到期日、自动续签、终止通知期，并起草给律师的续签/终止决策备忘。",
    steps: [
      {
        stepId: "scan",
        assignee: "contract_review",
        assigneeRoleId: "contract_review",
        task: "提取到期与续签条款并输出提醒备忘（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
];
