/**
 * Built-in named workflows (Claude for Legal / Suzie Law).
 * Copied into `<workspace>/lawmind/workflows/` when missing (see ensure-workflow-seeds.ts).
 */

import type { WorkspaceWorkflowTemplateFile } from "./workspace-workflow-templates.js";

export const BUILTIN_WORKFLOW_TEMPLATES: WorkspaceWorkflowTemplateFile[] = [
  {
    id: "nda-triage",
    name: "保密协议初审",
    namedAgent: "NDA Triager",
    description: "对 inbound NDA 做风险分级与要点摘要，供律师决定是否深入审查。",
    practiceArea: "commercial",
    deliverableType: "contract.review",
    riskLevel: "medium",
    audience: "solo",
    starterPrompt: "请对当前案件中的保密协议做初审：列出对己方不利条款、缺失定义与建议追问项。",
    acceptancePackRequired: true,
    requiredSources: ["NDA 文本"],
    steps: [
      {
        stepId: "review",
        assignee: "contract_reviewer",
        task: "审查 NDA 并输出 GREEN/YELLOW/RED 分级与条款摘要（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "contract-review",
    name: "合同审查意见",
    namedAgent: "Contract Review Analyst",
    description: "生成带章节结构的合同审查意见，便于进入审核台验收。",
    practiceArea: "commercial",
    deliverableType: "contract.review",
    riskLevel: "medium",
    audience: "solo",
    starterPrompt: "请审查本案主合同，输出分章节审查意见与风险等级。",
    acceptancePackRequired: true,
    requiredSources: ["主合同"],
    steps: [
      {
        stepId: "review",
        assignee: "contract_reviewer",
        task: "生成合同审查意见（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "vendor-agreement-review",
    name: "供应商协议审查",
    namedAgent: "Vendor Agreement Reviewer",
    description: "针对采购/服务协议的重点条款、责任上限与终止权做结构化审查。",
    practiceArea: "commercial",
    deliverableType: "contract.review",
    riskLevel: "medium",
    audience: "firm",
    starterPrompt: "请审查供应商协议：付款、交付、赔偿上限、知识产权与终止条款。",
    acceptancePackRequired: true,
    requiredSources: ["供应商协议"],
    steps: [
      {
        stepId: "review",
        assignee: "contract_reviewer",
        task: "供应商协议条款审查与风险清单（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "demand-letter",
    name: "律师函起草",
    namedAgent: "Demand Letter Drafter",
    description: "根据事实与诉求生成结构化律师函草稿，含待补充项清单。",
    practiceArea: "litigation",
    deliverableType: "letter.demand",
    riskLevel: "high",
    audience: "solo",
    starterPrompt: "请为本案起草律师函：先列出需律师确认的事实与诉求，再生成完整正文框架。",
    acceptancePackRequired: true,
    steps: [
      {
        stepId: "draft",
        assignee: "litigation_drafter",
        task: "起草律师函（matterId={{matterId}}），交付类型 letter.demand",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "matter-chronology",
    name: "案件时间线整理",
    namedAgent: "Chronology Builder",
    description: "按时间顺序整理关键事件、证据与待证事实（证据时间线）。",
    practiceArea: "litigation",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    starterPrompt: "请整理本案时间线：每个节点注明来源、争议点与下一步动作建议。",
    steps: [
      {
        stepId: "chronology",
        assignee: "case_analyst",
        task: "整理案件时间线与证据索引（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: true,
      },
    ],
  },
  {
    id: "evidence-index",
    name: "证据索引编制",
    namedAgent: "Evidence Indexer",
    description: "为案件卷宗建立证据目录与证明目的对照表。",
    practiceArea: "litigation",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    starterPrompt: "请根据现有材料编制证据索引：编号、来源、证明目的、待补强项。",
    steps: [
      {
        stepId: "index",
        assignee: "case_analyst",
        task: "编制证据索引表（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: true,
      },
    ],
  },
  {
    id: "due-diligence-review",
    name: "尽调审查表",
    namedAgent: "Due Diligence Reviewer",
    description: "多文档尽调：合同、函件与公开信息对照审查矩阵问题列。",
    practiceArea: "due_diligence",
    deliverableType: "contract.review",
    riskLevel: "high",
    audience: "firm",
    starterPrompt: "请启动尽调审查：先列出材料清单，再按尽调问题列逐项标注风险与来源。",
    acceptancePackRequired: true,
    requiredSources: ["目标公司材料包"],
    steps: [
      {
        stepId: "inventory",
        assignee: "case_analyst",
        task: "整理尽调材料清单与缺口（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: true,
      },
      {
        stepId: "review",
        assignee: "contract_reviewer",
        task: "按尽调审查表输出分文档风险摘要（matterId={{matterId}}）",
        dependsOn: ["inventory"],
        autoApprove: false,
      },
    ],
  },
  {
    id: "client-update-memo",
    name: "客户邮件摘要",
    namedAgent: "Client Update Writer",
    description: "面向客户的进展说明与下一步安排（邮件/备忘录语气）。",
    practiceArea: "client",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    starterPrompt: "请起草给客户的本案进展备忘录：已完成工作、当前风险、需客户确认事项与时间表。",
    steps: [
      {
        stepId: "memo",
        assignee: "client_communicator",
        task: "起草客户进展备忘录（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "compliance-research-memo",
    name: "合规研究报告",
    namedAgent: "Regulatory Research Analyst",
    description: "针对监管问题检索规范层级并输出可复核合规备忘录。",
    practiceArea: "compliance",
    deliverableType: "document.general",
    riskLevel: "medium",
    audience: "firm",
    starterPrompt: "请就本案监管问题做合规研究：规范层级、适用边界与结论清单。",
    steps: [
      {
        stepId: "research",
        assignee: "compliance_researcher",
        task: "合规检索与备忘录（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
  {
    id: "renewal-monitor",
    name: "合同续签监控",
    namedAgent: "Contract Renewal Monitor",
    description:
      "扫描主合同中的到期、续签与终止条款，输出续签提醒备忘（可配合 scheduleRunAt 预约执行）。",
    practiceArea: "commercial",
    deliverableType: "document.general",
    riskLevel: "low",
    audience: "solo",
    schedulable: true,
    starterPrompt:
      "请扫描本案主合同的到期日、自动续签、终止通知期，并起草给律师的续签/终止决策备忘。",
    steps: [
      {
        stepId: "scan",
        assignee: "contract_reviewer",
        task: "提取到期与续签条款并输出提醒备忘（matterId={{matterId}}）",
        dependsOn: [],
        autoApprove: false,
      },
    ],
  },
];
