/**
 * Renderer-facing request body types — single source with server Zod schemas.
 */
export type {
  ApprovalResolvePostRequest,
  AssistantProfileLearningPostRequest,
  AssistantUpsertRequest,
  ChatPostRequest,
  ChatResumeRequest,
  ContractReviewAcceptPostRequest,
  ContractReviewDraftPostRequest,
  DelegationCreateRequest,
  DeskSettingsPostRequest,
  DraftContentPatchBody,
  DraftReviewPostRequest,
  FirstrunWizardPostRequest,
  LawyerProfileLearningPostRequest,
  MatterCaseNoteRequest,
  MatterCreatePostRequest,
  MatterDeletePostRequest,
  MatterDisplayNamePostRequest,
  MatterInteractionRequest,
  MatterProfilePostRequest,
  MatterRolePostRequest,
  ModelsCustomPostRequest,
  ModelsDefaultPatchRequest,
  ModelsDraftWithModelPatchRequest,
  ModelsTestRequest,
  RedlineHunkResolvePostRequest,
  SessionCreatePostRequest,
  SessionDeletePostRequest,
  SessionPatchTitleRequest,
  TemplateEnabledPostRequest,
  TemplateRegisterPostRequest,
  TemplateScanPostRequest,
  WorkflowRunRequest,
  WorkspacePolicyPatchRequest,
} from "../../../../src/lawmind/platform/local-api-schemas.ts";
