import fs from "node:fs/promises";
import path from "node:path";
import { stdin as input, stdout as output } from "node:process";
import readline from "node:readline/promises";

type PresetId =
  | "qwen-only"
  | "qwen-chatlaw"
  | "deepseek-lawgpt"
  | "general-lexedge"
  | "general-partner";

type CliOptions = {
  preset?: PresetId;
  yes?: boolean;
};

function parseArgs(argv: string[]): CliOptions {
  const opts: CliOptions = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--yes" || arg === "-y") {
      opts.yes = true;
    } else if (arg === "--preset") {
      const value = argv[i + 1] as PresetId | undefined;
      if (value) {
        opts.preset = value;
        i += 1;
      }
    }
  }
  return opts;
}

async function choosePresetInteractive(): Promise<PresetId> {
  const rl = readline.createInterface({ input, output });
  try {
    output.write("\nLawMind Quick Setup\n");
    output.write("===================\n");
    output.write("Choose a starter preset:\n");
    output.write("  1) qwen-only        (no local legal service; general+legal both use Qwen)\n");
    output.write("  2) qwen-chatlaw     (Qwen + local ChatLaw at 127.0.0.1:8000)\n");
    output.write("  3) deepseek-lawgpt  (backup)\n");
    output.write("  4) general-lexedge  (framework route)\n");
    output.write("  5) general-partner  (partner local legal model)\n\n");
    const answer = (await rl.question("Select [1-5] (default: 1): ")).trim();
    if (answer === "2") {
      return "qwen-chatlaw";
    }
    if (answer === "3") {
      return "deepseek-lawgpt";
    }
    if (answer === "4") {
      return "general-lexedge";
    }
    if (answer === "5") {
      return "general-partner";
    }
    return "qwen-only";
  } finally {
    rl.close();
  }
}

function buildPresetContent(preset: PresetId): string {
  const header = [
    "# Auto-generated by: npm run lawmind:setup",
    "#",
    "# 商业化目标提示：请优先保障",
    "# 1) 稳定性（生产可用） 2) 成本可控 3) 合规可审计 4) 可规模复制",
    "#",
    "# Fill required values, then run:",
    "#   npm run lawmind:env:check",
    "#   npm run lawmind:smoke",
    "",
    "LAWMIND_INTERACTIVE_REVIEW=0",
    "",
  ];

  const commonGeneralQwen = [
    "# General model provider (Qwen / DashScope)",
    "LAWMIND_QWEN_API_KEY=",
    "LAWMIND_QWEN_MODEL=qwen-max",
    "",
  ];

  const commonGeneralDeepSeek = [
    "# General model provider (DeepSeek)",
    "LAWMIND_DEEPSEEK_API_KEY=",
    "LAWMIND_DEEPSEEK_MODEL=deepseek-chat",
    "",
  ];

  const legalChatLaw = [
    "# Legal model provider (ChatLaw self-hosted)",
    "LAWMIND_CHATLAW_BASE_URL=http://127.0.0.1:8000/v1",
    "LAWMIND_CHATLAW_API_KEY=local",
    "LAWMIND_CHATLAW_MODEL=chatlaw",
    "",
  ];

  const legalQwenSame = [
    "# Legal model: same Qwen endpoint (no local ChatLaw). Set API key to same as LAWMIND_QWEN_API_KEY.",
    "LAWMIND_CHATLAW_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1",
    "LAWMIND_CHATLAW_API_KEY=",
    "LAWMIND_CHATLAW_MODEL=qwen-plus",
    "",
  ];

  const legalLawGPT = [
    "# Legal model provider (LaWGPT self-hosted)",
    "LAWMIND_LAWGPT_BASE_URL=http://127.0.0.1:8000/v1",
    "LAWMIND_LAWGPT_API_KEY=local",
    "LAWMIND_LAWGPT_MODEL=lawgpt",
    "",
  ];

  const lexedge = [
    "# LexEdge integration",
    "LAWMIND_LEXEDGE_ENDPOINT=http://127.0.0.1:8787/retrieve",
    "LAWMIND_LEXEDGE_TOKEN=",
    "",
  ];

  const partner = [
    "# Partner local legal model",
    "LAWMIND_PARTNER_LEGAL_BASE_URL=http://127.0.0.1:8000/v1",
    "LAWMIND_PARTNER_LEGAL_API_KEY=local",
    "LAWMIND_PARTNER_LEGAL_MODEL=partner-legal-model",
    "",
  ];

  let body: string[] = [];
  if (preset === "qwen-only") {
    body = [...commonGeneralQwen, ...legalQwenSame];
  } else if (preset === "qwen-chatlaw") {
    body = [...commonGeneralQwen, ...legalChatLaw];
  } else if (preset === "deepseek-lawgpt") {
    body = [...commonGeneralDeepSeek, ...legalLawGPT];
  } else if (preset === "general-lexedge") {
    body = [...commonGeneralQwen, ...lexedge];
  } else {
    body = [...commonGeneralQwen, ...partner];
  }

  return [...header, ...body].join("\n");
}

async function confirmOverwrite(targetPath: string): Promise<boolean> {
  const rl = readline.createInterface({ input, output });
  try {
    const answer = (await rl.question(`File exists: ${targetPath}\nOverwrite? (y/N): `))
      .trim()
      .toLowerCase();
    return answer === "y" || answer === "yes";
  } finally {
    rl.close();
  }
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  const cwd = process.cwd();
  const target = path.resolve(cwd, ".env.lawmind");

  const preset = opts.preset ?? (await choosePresetInteractive());
  const content = buildPresetContent(preset);

  let exists = false;
  try {
    await fs.stat(target);
    exists = true;
  } catch {
    exists = false;
  }

  if (exists && !opts.yes) {
    const shouldOverwrite = await confirmOverwrite(target);
    if (!shouldOverwrite) {
      console.log("[LawMind] Setup cancelled.");
      return;
    }
  }

  await fs.writeFile(target, content, "utf8");

  console.log("[LawMind] .env.lawmind generated.");
  console.log(`preset=${preset}`);
  console.log(`path=${target}`);
  console.log("\nNext steps:");
  console.log("  npm run lawmind:env:check");
  console.log("  npm run lawmind:smoke");
}

main().catch((err) => {
  console.error("[LawMind] quick setup failed:", err);
  process.exitCode = 1;
});
